=== archies-coder/R2/src/main/resources/resource.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:simpleType name="version">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="className">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="paramName">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="exists">
        <xs:restriction base="xs:string">
            <xs:minLength value="3" />
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="Resource">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Desc" type="desc" minOccurs="0" maxOccurs="1" />
                <xs:choice maxOccurs="unbounded">
                    <xs:element name="Request" type="request"/>
                </xs:choice>
            </xs:sequence>
            <xs:attribute name="version" type="version" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="desc">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="method">
        <xs:restriction base="xs:string">
            <xs:enumeration value="GET"/>
            <xs:enumeration value="POST"/>
            <xs:enumeration value="PUT"/>
            <xs:enumeration value="DELETE"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="sql" >
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="sqlType" use="required" />
                <xs:attribute name="when" type="xs:string" />
                <xs:attribute name="className" type="className" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="sqlType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="query"/>
            <xs:enumeration value="update"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="request">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="Desc" type="desc" minOccurs="0" maxOccurs="1" />
            <xs:element name="Param" type="param" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Execute" type="execute" minOccurs="0" maxOccurs="unbounded" />
            <xs:element name="Sql" type="sql" minOccurs="0" maxOccurs="unbounded" />
        </xs:choice>
        <xs:attribute name="method" type="method" use="required" />
        <xs:attribute name="status" type="xs:int"/>
        <xs:attribute name="item" type="xs:boolean" default="false" />
    </xs:complexType>

    <xs:complexType name="param">
        <xs:attribute name="name" type="paramName" use="required" />
        <xs:attribute name="blank" type="xs:boolean" default="false" />
        <xs:attribute name="num" type="xs:boolean" default="false" />
        <xs:attribute name="required" type="xs:boolean" default="false" />
        <xs:attribute name="max" type="xs:double" />
        <xs:attribute name="min" type="xs:double" />
        <xs:attribute name="maxLen" type="xs:int" />
        <xs:attribute name="minLen" type="xs:int" />
        <xs:attribute name="pattern" type="xs:string" />
        <xs:attribute name="exists" type="exists" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="execute">
        <xs:attribute name="className" type="className" use="required" />
    </xs:complexType>

</xs:schema>

=== archies-coder/R2/src/test/resources/apple.xml
<?xml version="1.0" encoding="UTF-8" ?>
<mtg:Resource xmlns:mtg="http://xml.metamug.net/resource/1.0"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://xml.metamug.net/resource/1.0 http://xml.metamug.net/schema/resource.xsd" version="1.1">

    <mtg:Desc>Contains records for data type apple</Desc>

    <mtg:Request method="GET" item="true" status="200">
        <mtg:Param name="t" blank="true" min="1" exists="table.column" />
        <mtg:Param name="v" minLen="1" maxLen="500" />
        <mtg:Param name="param1" minLen="5" maxLen="50" />

        <mtg:Sql when="$q eq 1" type="query">
            select * from employee where employee_name = $v
        </mtg:Sql>
        <mtg:Sql type="query" when="$q eq 2" className="com.mtg.Urls">
            select * from employee
            where employee_name = $param1
            and employee_id = $id
        </mtg:Sql>
        <mtg:Sql when="$q eq 3" type="update">
            update employee set employee_name = $param2 where employee_id=$id
        </mtg:Sql>
    </mtg:Request>

    <mtg:Request method="POST" status="201">
        <mtg:Desc>mtg:Request for creating an employee record.</mtg:Desc>
        <mtg:Sql type="update">
            insert into employee
            (employee_name, employee_id)
            values($name, $id)
        </mtg:Sql>

        <mtg:Execute className="com.mtg.Apple" />

    </mtg:Request>

    <!--derived from mtg:Request -->
    <mtg:Request method="PUT" item="true">
        <mtg:Execute className="com.mtg.Apple" />
    </mtg:Request>

    <mtg:Request method="GET" item="false">
        <mtg:Sql type="query" when="$item lt 1">select * from employee where employee_id=12
        </mtg:Sql>
    </mtg:Request>

    <mtg:Request method="DELETE" item="true">
        <mtg:Sql type="update">delete * from employee where employee_id=$id
        </mtg:Sql>
    </mtg:Request>

</mtg:Resource>
